### ISSUE TITLE
Do you have mono configs for KITTI?

### ISSUE THREAD

**Issue by synsin0** [cskkxjk/MonoNeRD#2]
I see the stereo configs for KITTI and mono configs for Waymo OD. Do you have mono configs for KITTI? Thanks.

**Comment by cskkxjk** [comment]
> I see the stereo configs for KITTI and mono configs for Waymo OD. Do you have mono configs for KITTI? Thanks.
We inherit the ''stereo'' term from LIGA, which loads both left and right camera images in the dataloader.
The difference of mono and stereo configs is whether to use right camera supervisions.
The default KITTI config does not use the right camera supervisions, so you can directly use this config as monocular setting.
See:
https://github.com/cskkxjk/MonoNeRD/blob/2d15e6f329e0bf39e99a952f5cb39ebdeed05692/configs/stereo/kitti_models/mononerd.3d-and-bev.yaml#L21
