### ISSUE TITLE
Why monocular methods require the stereo information (of kitti dataset)?

### ISSUE THREAD

**Issue by Hongbin98** [cskkxjk/MonoNeRD#3]
First of all, thanks for your work to the community!

I am new in this area, and I wonder why mononerd needs the right color images of kitti dataset in the evaluation stage?

**Comment by cskkxjk** [comment]
In fact, mononerd doesn't require the right camera images during evaluation, we load right camera images in the dataloader for convenience. 
This is used to conduct ablation studies  in Table 4 of our supplementary to verify the effectiveness of the supervision of right camera view.
If it's still bother, you can comment out the load code of the right camera images, this won't affect the final evaluation results.

**Comment by Merealtea** [comment]
And I have the same question  about lidar encoder. As a model based on the image, why there is a lidar encoder on it?

**Comment by cskkxjk** [comment]
> And I have the same question about lidar encoder. As a model based on the image, why there is a lidar encoder on it?

Hi! mononerd is based on [LIGA-Stereo](https://github.com/xy-guo/LIGA-Stereo), which uses lidar-extrated features to guide the learning of lifted 3D image features. 
We keep it the same for experiments on KITTI since LIGA-Stereo provides their KITTI lidar checkpoint, but no lidar models are required on Waymo experiments.

**Comment by Merealtea** [comment]
> > And I have the same question about lidar encoder. As a model based on the image, why there is a lidar encoder on it?
> 
> Hi! mononerd is based on [LIGA-Stereo](https://github.com/xy-guo/LIGA-Stereo), which uses lidar-extrated features to guide the learning of lifted 3D image features. We keep it the same for experiments on KITTI since LIGA-Stereo provides their KITTI lidar checkpoint, but no lidar models are required on Waymo experiments.

I see. So if I delete the point encoder module in the network, this model still can run fine, right?

**Comment by cskkxjk** [comment]
> > > And I have the same question about lidar encoder. As a model based on the image, why there is a lidar encoder on it?
> > 
> > 
> > Hi! mononerd is based on [LIGA-Stereo](https://github.com/xy-guo/LIGA-Stereo), which uses lidar-extrated features to guide the learning of lifted 3D image features. We keep it the same for experiments on KITTI since LIGA-Stereo provides their KITTI lidar checkpoint, but no lidar models are required on Waymo experiments.
> 
> I see. So if I delete the point encoder module in the network, this model still can run fine, right?

yeap, you can refer to the [waymo config](https://github.com/cskkxjk/MonoNeRD/blob/main/configs/mono/waymo_models/waymo_kitti_format.yaml) for details, and the KITTI results withou lidar imitation would definitly drop.
