### ISSUE TITLE
How to run inference on a single gpu?

### ISSUE THREAD

**Issue by Hongbin98** [cskkxjk/MonoNeRD#6]
When I try to run `./scripts/dist_test_ckpt.sh ${NUM_GPUS=1} ./configs/stereo/kitti_models/mononerd.yaml ./ckpt/pretrained_mononerd.pth`

It still runs the cmd `python -m torch.distributed.launch --nproc_per_node=8 tools/test.py --launcher pytorch --save_to_file --cfg_file pretrained-config.yaml --ckpt checkpoint.pth`

Besides, the code fails when I run  `python -m torch.distributed.launch --nproc_per_node=1 tools/test.py --launcher pytorch --save_to_file --cfg_file pretrained-config.yaml --ckpt checkpoint.pth` or  `python tools/test.py --save_to_file --cfg_file pretrained-config.yaml --ckpt checkpoint.pth`

Looking forward for your reply!

**Comment by cskkxjk** [comment]
If you run the training or test code on an multi-GPU device, the following code can help which only use GPU 0:
`CUDA_VISIBLE_DEVICES=0 ./scripts/dist_test_ckpt.sh 1 ./configs/stereo/kitti_models/mononerd.yaml ./ckpt/pretrained_mononerd.pth`

**Comment by Hongbin98** [comment]
Thanks for your reply! :)
