### ISSUE TITLE
How to get the score of all classes?

### ISSUE THREAD

**Issue by Hongbin98** [cskkxjk/MonoNeRD#7]
In the monocular 3D object detection task, the file `'mononerd/models/detectors_mono/stereo_detector3d_template.py'` contains the function `post_processing()` which is used to generate predictions of KITTI dataset.

My question is: **How can I get all scores of an object (one of the objects belongs to the same image) instead of the highest one?**

For example, for a car object, its scores may be [0.1333, 0.04, 0.05] (corresponding to 3 classes). I want to get the whole output [0.1333, 0.04, 0.05] rather than the highest value, i.e., 0.1333

Thanks for your patient reply :)

**Comment by Hongbin98** [comment]
Hello, I am so sad to say that setting the post_process_cfg.OUTPUT_RAW_SCORE to True does not make sense, i.e., it still outputs the highest score.

Since your code relies on a very complex environment for me, I could just run it on my docker and have no idea about how to debug it on my PC. 

If it is possible for you to tell me which variant contains the score distributions (If you could run your code in the debugging mode)? I think it must be somewhere (Since we have to output the score of each object).

I am sincerely willing to compare my work with your method and cite it as an important baseline.

Looking forward to your reply.

**Comment by cskkxjk** [comment]
Hi, i've been away from my previous company during intern for some time now, and currently i'm preparing for my next work and future job interviews. At the moment, i lack the necessary computing resources for debugging.
If possible, please send me an email `xujunkai@zju.edu.cn/zjuxjk2333@gmail.com`, and i will provide you with my contact information and detail how to debug within docker container.

**Comment by Hongbin98** [comment]
Thanks for your reply! 

However, I should not disrupt you too much if you lack the necessary computing resources.

I would try my best to figure it out.

Please take it easy~

**Comment by cskkxjk** [comment]
> Thanks for your reply!
> 
> However, I should not disrupt you too much if you lack the necessary computing resources.
> 
> I would try my best to figure it out.
> 
> Please take it easy~

Ok, i assume i could acquire some GPU devices later next month, if this problem still bother you, feel free to contact me!
